/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author rajat
 */
public class deleteBuyer extends javax.swing.JFrame {

    /**
     * Creates new form deleteBuyer
     */
    public deleteBuyer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        search = new javax.swing.JTextField();
        ad = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        ad2 = new javax.swing.JLabel();
        ad3 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ad4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(244, 165, 112));
        kGradientPanel1.setkStartColor(new java.awt.Color(131, 192, 239));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("DELETE BUYER");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));
        kGradientPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, 620, 10));
        kGradientPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 330, -1));

        ad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ad.setText("CONTACT :");
        ad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adMouseClicked(evt);
            }
        });
        kGradientPanel1.add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));
        kGradientPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 620, 20));

        ad2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ad2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ad2.setText("ADDRESS :");
        ad2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ad2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ad2MouseClicked(evt);
            }
        });
        kGradientPanel1.add(ad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        ad3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ad3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ad3.setText("Contact No :");
        ad3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ad3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ad3MouseClicked(evt);
            }
        });
        kGradientPanel1.add(ad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        contact.setEditable(false);
        kGradientPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 330, -1));

        name.setEditable(false);
        kGradientPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 330, -1));

        address.setEditable(false);
        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 330, 110));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/eraser final 112233.png"))); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/cancel final 112233.png"))); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, -1));

        ad4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ad4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ad4.setText("NAME :");
        ad4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ad4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ad4MouseClicked(evt);
            }
        });
        kGradientPanel1.add(ad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/delete ori 1122.png"))); // NOI18N
        jButton3.setText("Delete");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 100, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/search final 1122.png"))); // NOI18N
        jButton4.setText("Search");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adMouseClicked
       //
    }//GEN-LAST:event_adMouseClicked

    private void ad2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ad2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ad2MouseClicked

    private void ad3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ad3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ad3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // CLEAR  UPDATE BUYER SCREEN :
        name.setText("");
        contact.setText("");
        address.setText("");
        search.setText("");
        search.setEditable(true);
                contact.setEditable(true);
                address.setEditable(true);
                name.setEditable(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // CLOSE THE UPDATE-BUYER
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ad4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ad4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ad4MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          // TO DELETE BUYER IN LIST
        String searchno=search.getText();
        int a=JOptionPane.showConfirmDialog(null,"DO YOU WANT TO DELETE ?","select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
        try
        {
         String sql="DELETE FROM `newbuyer1` WHERE ContactNo='"+searchno+"' ";
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/shop&sell1","root","");            
            PreparedStatement pst=con.prepareStatement(sql);
            pst.executeUpdate();
            
             JOptionPane.showMessageDialog(null,"Contact Delete Sucessfully ...");
                 name.setText("");
                contact.setText("");
                address.setText(""); 
                search.setText("");
                search.setEditable(true);
                contact.setEditable(false);
                address.setEditable(false);
                name.setEditable(false);
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,"Connection Error");
        } 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
               
         // SEARCH BUTTON CODE IN DELETE BUYER :
        String contactNo=search.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/shop&sell1","root","");
            String sql = "Select * from newbuyer1 where ContactNo=? ";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,contactNo);
            ResultSet rs=pst.executeQuery();
            if(rs.next()){

                name.setText(rs.getString("name"));
                contact.setText(rs.getString("ContactNo"));
                address.setText(rs.getString("address"));
                search.setEditable(false);
                contact.setEditable(false);
                address.setEditable(false);
                name.setEditable(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null," Contact Not Exist  ");

            }
            con.close();

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Connection Error");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deleteBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deleteBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deleteBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deleteBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deleteBuyer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ad;
    private javax.swing.JLabel ad2;
    private javax.swing.JLabel ad3;
    private javax.swing.JLabel ad4;
    private javax.swing.JTextArea address;
    private javax.swing.JTextField contact;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}

