/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.mysql.jdbc.Statement;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import java.util.Date;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rajat
 */
public class face2 extends javax.swing.JFrame {
    public int finalTotal=0;

    /**
     * Creates new form face2
     */
    
   /* public Connection getConnection()
    {
        try{
        Class.forName("com.mysql.jdbc.Driver");
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        Connection con=null;
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bills","root","");
        }catch(Exception ex)
        {
        System.out.println(ex.getMessage());
        }
        return con;
        }*/
    int flag=0;
    public face2() {
        initComponents();
        this.setLocationRelativeTo(null);
        SimpleDateFormat dFormat=new SimpleDateFormat("dd-MM-yyyy");
        Date date=new Date();
        jLabel22.setText(dFormat.format(date));
        
        
        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now=LocalDateTime.now();
        jLabel23.setText(dtf.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel9 = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1150, 580));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/close-window.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 40, 40);

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, 40, 580));

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/back final 1122.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        kGradientPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 30));

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 580));

        kGradientPanel3.setkEndColor(new java.awt.Color(0, 51, 102));
        kGradientPanel3.setkStartColor(new java.awt.Color(0, 51, 102));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADDRESS :");
        kGradientPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        kGradientPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 250, -1));
        kGradientPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 650, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PHONE NO. :");
        kGradientPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 80, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        kGradientPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 250, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DATE :");
        kGradientPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 50, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("BUYER DETAILS");
        kGradientPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("TIME :");
        kGradientPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 50, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("NAME :");
        kGradientPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 150, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 80, 150, 20));

        getContentPane().add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 1080, 120));

        kGradientPanel5.setBackground(new java.awt.Color(204, 204, 204));
        kGradientPanel5.setkEndColor(new java.awt.Color(204, 204, 204));
        kGradientPanel5.setkStartColor(new java.awt.Color(204, 204, 204));
        kGradientPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "QUANTITY", "RATE", "DESCRIPTION", "SUBTOTAL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        kGradientPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 360));

        getContentPane().add(kGradientPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 780, 360));

        kGradientPanel6.setkEndColor(new java.awt.Color(0, 34, 68));
        kGradientPanel6.setkStartColor(new java.awt.Color(0, 34, 68));
        kGradientPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TIME :");
        kGradientPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 50, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CALCULATION DETAILS :");
        kGradientPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("RETURNED AMOUNT :");
        kGradientPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("TOTAL :");
        kGradientPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/eraser final 112233.png"))); // NOI18N
        jButton2.setText("Clear");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/print final.png"))); // NOI18N
        jButton4.setText("Print");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));
        kGradientPanel6.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 120, -1));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 120, -1));

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 120, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("AMOUNT PAID :");
        kGradientPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, -1));

        getContentPane().add(kGradientPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 290, 360));

        kGradientPanel4.setkEndColor(new java.awt.Color(85, 119, 153));
        kGradientPanel4.setkStartColor(new java.awt.Color(85, 119, 153));
        kGradientPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRODUCT DETAILS");
        kGradientPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));
        kGradientPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DESCRIPTION");
        kGradientPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 90, -1));
        kGradientPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 320, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PRODUCT ID ");
        kGradientPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 80, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PRODUCT NAME");
        kGradientPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 110, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("QUANTITY");
        kGradientPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 80, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        kGradientPanel4.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 70, -1));
        kGradientPanel4.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 200, -1));
        kGradientPanel4.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 80, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("RATE");
        kGradientPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 40, -1));
        kGradientPanel4.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 110, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/add-to-cart final 11 22.png"))); // NOI18N
        jButton1.setToolTipText("Add to List");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 50, 50));

        getContentPane().add(kGradientPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 1070, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       face1 rgf = new face1();  // BACK TO FACE 1
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // GET NAME FROM jTextField1
       String name=jTextField1.getText();
       try
       {
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/shop&sell1","root","");            
           java.sql.Statement pst=con.createStatement();
           ResultSet rs=pst.executeQuery("Select * from newbuyer1 where name like '"+name+"%'");
           if(rs.next())
           {
           jTextField1.setText(rs.getString(1));
           jTextField2.setText(rs.getString(2));
           jTextField4.setText(rs.getString(3));
          
           }
           else
           {
           jTextField2.setText("");
           jTextField4.setText("");
           
           }
       }
       catch(Exception e)
       {
      JOptionPane.showMessageDialog(null,e);
       }
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // GET CONTACTNO FROM jTextField2
        String contact=jTextField2.getText();
       try
       {
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/shop&sell1","root","");            
           java.sql.Statement pst=con.createStatement();
           ResultSet rs=pst.executeQuery("Select * from newbuyer1 where ContactNo like '"+contact+"%'");
           if(rs.next())
           {
           jTextField1.setText(rs.getString(1));
           jTextField2.setText(rs.getString(2));
           jTextField4.setText(rs.getString(3));
          
           }
           else
           {
           jTextField1.setText("");
           jTextField4.setText("");
           
           }
       }
       catch(Exception e)
       {
      JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
         // GET CONTACTNO FROM jTextField2
        String pid=jTextField5.getText();
       try
       {
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/shop&sell1","root","");            
           java.sql.Statement pst=con.createStatement();
           ResultSet rs=pst.executeQuery("Select * from product where pid like '"+pid+"%'");
           if(rs.next())
           {
           jTextField6.setText(rs.getString(2));
           jTextField7.setText("1");
           jTextField8.setText(rs.getString(3));
          jTextField3.setText(rs.getString(4));
           }
           else
           {
           jTextField6.setText("");
           jTextField7.setText("");
           jTextField8.setText("");
            jTextField3.setText("");
           
           }
       }
       catch(Exception e)
       {
      JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // ADD ITEM IN TABLE IN FACE2
        int price=Integer.parseInt(jTextField8.getText());
        int quantity=Integer.parseInt(jTextField7.getText());
        int total=price*quantity;
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[]{jTextField6.getText(),quantity,price,jTextField3.getText(),total});
        finalTotal=finalTotal+total;
        String finalTotal1=String.valueOf(finalTotal);
        jTextField9.setText(finalTotal1);
       // if(rb1.isSelected())
          /* jTextField10.setText(finalTotal1-finalTotal1*5/10);*/
            
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // PAID AMOUNT
       String paidAmount=jTextField10.getText();
       int z=Integer.parseInt(paidAmount);
       finalTotal=z-finalTotal;
       String finalToatal=String.valueOf(finalTotal);
       jTextField11.setText(finalToatal);
       jTextField11.setEditable(false);
       
        
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new face2().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//Save New Customer Detail 


/*DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
try{
    for(int i=0;i<jTable1.getRowCount();i++)
        {
           String query = "INSERT INTO `buyer`(`name`, `phno`, `address`, `date`, `time`, `pname`, `qty`, `rate`, `descr`, `subtotal`) VALUES (?,?,?,?,?,?,?,?,?,?)";
                
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bills","root","");            
           
            PreparedStatement pst=con.prepareStatement(query);
            
            pst.setString(1,jTextField1.getText());
            pst.setString(2,jTextField2.getText());
             pst.setString(3,jTextField4.getText());
             
             pst.setString(4,jTable1.getValueAt(i,0).toString());
             pst.setString(5,jTable1.getValueAt(i,1).toString());
             pst.setString(6,jTable1.getValueAt(i,2).toString());
             pst.setString(7,jTable1.getValueAt(i,3).toString());
             pst.setString(8,jTable1.getValueAt(i,4).toString());
              
            pst.executeUpdate();
        }    
 
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error in adding Buyer Details");
        }


*/
// PRINT IN FACE 2/*
       
        String name=jTextField1.getText();
        String phoneno=jTextField2.getText();
        String address=jTextField4.getText();
        String path="D:\\";
        com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
        try
        {
        PdfWriter.getInstance(doc,new FileOutputStream(path+""+name+" "+jLabel22.getText()+".pdf"));
        doc.open();
        Paragraph paragraph1=new Paragraph("                            SHOP & SELL BILLING SYSTEM\n                            CONTACT NO :(+91)9166094545\n\n");
        doc.add(paragraph1);
         Paragraph paragraph2=new Paragraph("DATE & TIME :"+jLabel22.getText()+"  "+jLabel23.getText()+"\nBuyer Details :\nName :"+name+"\nContact No:"+phoneno+"\nAddress :"+address+"\n\n");
        doc.add(paragraph2);
        PdfPTable tb1=new PdfPTable(5);
        tb1.addCell("Name");
        tb1.addCell("Quantity");
        tb1.addCell("Rate");
        tb1.addCell("Description");
        tb1.addCell("Sub Total");
        for(int i=0;i<jTable1.getRowCount();i++)
        {
        String n=jTable1.getValueAt(i,0).toString();
        String d=jTable1.getValueAt(i,1).toString();
        String r=jTable1.getValueAt(i,2).toString();
        String q=jTable1.getValueAt(i,3).toString();
        String s=jTable1.getValueAt(i,4).toString();
        tb1.addCell(n);
        tb1.addCell(d);
        tb1.addCell(r);
        tb1.addCell(q);
        tb1.addCell(s);
        }
        doc.add(tb1);
        Paragraph paragraph3=new Paragraph("\nTotal :"+jTextField9.getText()+"\nPaid Amount :"+jTextField10.getText()+"\nReturn amount :"+jTextField11.getText()+"\n\nTHANK YOU FOR VISITING...\n SHOP & SELL");
        doc.add(paragraph3);
        JOptionPane.showMessageDialog(null," BILL  GENERATED");
        setVisible(false);
        new face2().setVisible(true);
        
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,e);
        }
        doc.close();
        
        
         
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(face2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(face2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(face2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(face2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new face2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    // End of variables declaration//GEN-END:variables
}

